/**
 * build-index.mjs — K1 (llmwiki-uplift)
 *
 * Walks wiki/content/ko/**\/*.md (excluding terms.yaml / dummy files),
 * parses YAML frontmatter with gray-matter, then regenerates wiki/index.md.
 *
 * Categories (§2.1 design doc 5-axis):
 *   1. Agenda    — content/ko/agenda/
 *   2. Sessions  — content/ko/session/
 *   3. Docs      — content/ko/doc/
 *   4. Glossary  — content/ko/glossary/
 *   5. Schema Summary (static, appended at end)
 *
 * Trust label badges (SCHEMA.md 4-tier):
 *   machine        → ⚠️
 *   reviewed       → 🔵
 *   native         → 🟢
 *   author-verified → 🟢✓
 *
 * Run: node scripts/build-index.mjs (from wiki/ directory)
 * AUTO-GENERATED output: wiki/index.md — DO NOT EDIT MANUALLY.
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join, resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import matter from 'gray-matter';

const __filename = fileURLToPath(import.meta.url);
const __dir = dirname(__filename);
const WIKI_ROOT = resolve(__dir, '..');
const CONTENT_KO = join(WIKI_ROOT, 'content', 'ko');
const INDEX_OUT = join(WIKI_ROOT, 'index.md');

/** Trust badge text */
function trustBadge(trust) {
  const map = {
    'machine': '⚠️',
    'reviewed': '🔵',
    'native': '🟢',
    'author-verified': '🟢✓',
  };
  return map[trust] || '—';
}

/** Read all .md files from a subdirectory, return array of parsed entries. */
function readCategory(subdir) {
  const dir = join(CONTENT_KO, subdir);
  let files;
  try {
    files = readdirSync(dir);
  } catch {
    return [];
  }

  const entries = [];
  for (const file of files) {
    if (!file.endsWith('.md')) continue;
    const fullPath = join(dir, file);
    try {
      const raw = readFileSync(fullPath, 'utf-8');
      const { data } = matter(raw);
      // Skip dummy/placeholder entries
      if (data.slug === '00-dummy' || file.startsWith('00-')) continue;
      entries.push({ file, path: `content/ko/${subdir}/${file}`, data });
    } catch {
      // Skip unparseable files
    }
  }
  return entries;
}

/** Format agenda table rows. */
function agendaRows(entries) {
  if (!entries.length) return '_No entries yet._\n';
  const header = '| id | slug | title | category | status | trust |\n|----|------|-------|----------|--------|-------|\n';
  const rows = entries.map(({ data }) =>
    `| ${data.id ?? '—'} | ${data.slug ?? '—'} | ${data.title ?? '—'} | ${data.category ?? '—'} | ${data.status ?? '—'} | ${trustBadge(data.trust)} |`
  ).join('\n');
  return header + rows + '\n';
}

/** Normalize a date value (may be JS Date object from YAML parser) to YYYY-MM-DD string. */
function normalizeDate(val) {
  if (!val) return '—';
  if (val instanceof Date) {
    const pad = n => String(n).padStart(2, '0');
    return `${val.getFullYear()}-${pad(val.getMonth() + 1)}-${pad(val.getDate())}`;
  }
  return String(val);
}

/** Format session table rows. */
function sessionRows(entries) {
  if (!entries.length) return '_No entries yet._\n';
  const header = '| date | slug | title | type | speaker |\n|------|------|-------|------|---------|\n';
  const rows = entries.map(({ data }) =>
    `| ${normalizeDate(data.date)} | ${data.slug ?? '—'} | ${data.title ?? '—'} | ${data.session_type ?? '—'} | ${data.speaker ?? '—'} |`
  ).join('\n');
  return header + rows + '\n';
}

/** Format doc table rows. */
function docRows(entries) {
  if (!entries.length) return '_No entries yet._\n';
  const header = '| slug | title | doc_type |\n|------|-------|----------|\n';
  const rows = entries.map(({ data }) =>
    `| ${data.slug ?? '—'} | ${data.title ?? '—'} | ${data.doc_type ?? '—'} |`
  ).join('\n');
  return header + rows + '\n';
}

/** Format glossary summary row. */
function glossaryRow(entries) {
  const count = entries.length;
  if (!count) return '_No glossary files yet._\n';
  return `| terms.yaml | ${count} term files | glossary |\n`;
}

// --- Gather data ---
const agendaEntries = readCategory('agenda')
  .sort((a, b) => (a.data.id ?? 0) - (b.data.id ?? 0));

const sessionEntries = readCategory('session')
  .sort((a, b) => normalizeDate(a.data.date).localeCompare(normalizeDate(b.data.date)));

const docEntries = readCategory('doc')
  .sort((a, b) => String(a.data.title ?? '').localeCompare(String(b.data.title ?? '')));

// Glossary: count terms.yaml separately (it's YAML, not YAML frontmatter)
let glossaryCount = 0;
try {
  const glossaryDir = join(CONTENT_KO, 'glossary');
  const gFiles = readdirSync(glossaryDir);
  glossaryCount = gFiles.filter(f => f.endsWith('.yaml') || f.endsWith('.yml')).length;
} catch { /* no glossary dir */ }

const totalPages = agendaEntries.length + sessionEntries.length + docEntries.length;
const now = new Date().toISOString();

// --- Build markdown ---
const md = `<!-- AUTO-GENERATED by scripts/build-index.mjs. DO NOT EDIT MANUALLY. -->
<!-- Last generated: ${now} | Pages: ${totalPages} -->

# climate-assembly.org — Wiki Index

> Korea's first national Climate Citizens' Assembly (2026).
> 200 deliberating citizens, Article 19-2 Carbon Neutrality Framework Act.
> Languages: ko / en (M4+: ja / zh / es)

---

## 1. Agenda (의제) — ${agendaEntries.length} pages

${agendaRows(agendaEntries)}
## 2. Sessions (세션) — ${sessionEntries.length} pages

${sessionRows(sessionEntries)}
## 3. Docs (문서) — ${docEntries.length} pages

${docRows(docEntries)}
## 4. Glossary (용어집)

| file | count | type |
|------|-------|------|
${glossaryCount ? `| terms.yaml | ${glossaryCount} file(s) | glossary |\n` : '_No glossary files yet._\n'}
## 5. Schema Summary

- Translation status 4 tiers: machine ⚠️ / reviewed 🔵 / native 🟢 / author-verified 🟢✓
- License: CC BY-SA 4.0
- SCHEMA.md §1: Frontmatter required fields per type
- SHOWCASE_STYLE.md: 5 principles for non-ko pages
- Layer model: Raw (L1, read-only) → Wiki (L2, sub-editable) → Schema (L3, PM-only)
`;

writeFileSync(INDEX_OUT, md, 'utf-8');
console.log(`[build-index] wiki/index.md written — ${totalPages} pages, generated at ${now}`);
